// packages/create-webui/src/components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-9 w-full rounded-md border border-input bg-popover px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };

// packages/cli/examples/download/src/lib/components/ui/input/input.svelte
<script lang="ts">
  import { cn } from "$lib/utils.ts";

  type Props = {
    id?: string;
    class?: string;
    value?: string;
    type?: string;
    placeholder?: string;
    oninput?: (e: Event) => void;
    disabled?: boolean;
  };

  let {
    id,
    class: className,
    value = "",
    type = "text",
    placeholder,
    oninput,
    disabled = false,
  }: Props = $props();
</script>

<input
  {id}
  class={cn(
    "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
    className,
  )}
  {type}
  {value}
  {placeholder}
  {oninput}
  {disabled}
/>
